#|Andrés Sebastián Arteaga Cabezas
Ejercicio 27 Tema 3: Inducción de Conceptos Umbral|#

(#%require racket)
(include "T3Ejercicio20.rkt")

(define (score-TC conTC PSET NSET)
  (let((pc (let*((count 0))
             (map (lambda (x)
                    (if(equal? x #t)
                       (set! count (+ 1 count))
                       'null))
                  (map (lambda (x) (match-TC conTC x))
                       (map(lambda(x)(reverse(cdr(reverse x))))(cdr PSET))))
             count))
       (nc (let*((count 0))
             (map (lambda (x)
                    (if(equal? x #f)
                       (set! count (+ 1 count))
                       'null))
                  (map (lambda (x) (match-TC conTC x))
                       (map(lambda(x)(reverse(cdr(reverse x))))(cdr NSET))))
             count)))
    (/ (+ pc nc) (+ (- (length PSET) 1) (- (length NSET) 1)))))

;;Nota para ejecutar retirar #|codigo.........|#
;;esta es otra forma de poner comentarios

#|(score-TC '(3 (soleado)(*)(10 40)(si))
          '(((clima (soleado nublado lluvioso))
             (temperatura 'numerico)
             (humedad 'numerico)
             (viento (si no))
             (clase (+ -)))
            (soleado 12 20 no +)
            (soleado 15 20 si +)
            (soleado 10 25 no +)
            (soleado 10 60 si +)
            (soleado 16 20 no +)
            (soleado 17 20 si +)
            (soleado 10 19 si +)
            (soleado 5 27 si +)
            (soleado 10 20 no +)
            (soleado 1 21 si +))
          '(((clima (soleado nublado lluvioso))
             (temperatura 'numerico)
             (humedad 'numerico)
             (viento (si no))
             (clase (+ -)))
            (soleado 12 20 no -)
            (soleado 15 20 si -)
            (soleado 10 25 no -)
            (soleado 10 60 si -)
            (soleado 16 20 no -)
            (soleado 17 20 si -)
            (soleado 10 19 si -)
            (soleado 5 27 si -)
            (soleado 10 20 no -)
            (soleado 1 21 si -)))|#